import { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { useAuth } from '../contexts/AuthContext'
import { supabase, Event, Wedding } from '../lib/supabase'
import { Layout } from '../components/Layout'
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from '../components/Card'
import { Button } from '../components/Button'
import { EventCard } from '../components/EventCard'
import { CreateEventModal } from '../components/CreateEventModal'
import toast from 'react-hot-toast'

const EventsPage = () => {
  const { user } = useAuth()
  const navigate = useNavigate()
  const [events, setEvents] = useState<Event[]>([])
  const [wedding, setWedding] = useState<Wedding | null>(null)
  const [loading, setLoading] = useState(true)
  const [showCreateModal, setShowCreateModal] = useState(false)

  useEffect(() => {
    fetchWeddingAndEvents()
  }, [user])

  const fetchWeddingAndEvents = async () => {
    if (!user) return

    try {
      // Get couple and wedding
      const { data: coupleData } = await supabase
        .from('couples')
        .select('*')
        .or(`user1_id.eq.${user.id},user2_id.eq.${user.id}`)
        .single()

      if (!coupleData) {
        toast.error('You need to be in a couple to view events')
        navigate('/dashboard')
        return
      }

      const { data: weddingData } = await supabase
        .from('weddings')
        .select('*')
        .eq('couple_id', coupleData.id)
        .single()

      if (!weddingData) {
        toast.error('Please create a wedding first')
        navigate('/wedding/create')
        return
      }

      setWedding(weddingData)

      // Fetch events
      const { data: eventsData, error } = await supabase
        .from('events')
        .select('*')
        .eq('wedding_id', weddingData.id)
        .order('date', { ascending: true })

      if (error) throw error
      setEvents(eventsData || [])
    } catch (error: any) {
      toast.error(error.message || 'Failed to load events')
    } finally {
      setLoading(false)
    }
  }

  const handleEventCreated = () => {
    setShowCreateModal(false)
    fetchWeddingAndEvents()
    toast.success('Event created successfully!')
  }

  const handleDeleteEvent = async (eventId: string) => {
    if (!confirm('Are you sure you want to delete this event?')) return

    try {
      const { error } = await supabase.from('events').delete().eq('id', eventId)
      if (error) throw error

      toast.success('Event deleted successfully')
      fetchWeddingAndEvents()
    } catch (error: any) {
      toast.error(error.message || 'Failed to delete event')
    }
  }

  if (loading) {
    return (
      <Layout>
        <div className="flex items-center justify-center h-64">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary-400"></div>
        </div>
      </Layout>
    )
  }

  const autoGeneratedEvents = events.filter((e) => e.auto_generated)
  const customEvents = events.filter((e) => !e.auto_generated)

  return (
    <Layout>
      <div className="space-y-6">
        {/* Header */}
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-3xl font-bold text-gray-900">Wedding Events</h1>
            <p className="text-gray-600 mt-1">
              Manage all your wedding events and ceremonies
            </p>
          </div>
          <Button onClick={() => setShowCreateModal(true)}>
            + Add Custom Event
          </Button>
        </div>

        {/* Stats */}
        <div className="grid md:grid-cols-4 gap-4">
          <Card>
            <CardContent className="pt-6">
              <div className="text-center">
                <p className="text-3xl font-bold text-primary-400">{events.length}</p>
                <p className="text-sm text-gray-600 mt-1">Total Events</p>
              </div>
            </CardContent>
          </Card>
          <Card>
            <CardContent className="pt-6">
              <div className="text-center">
                <p className="text-3xl font-bold text-primary-400">{autoGeneratedEvents.length}</p>
                <p className="text-sm text-gray-600 mt-1">Auto-Generated</p>
              </div>
            </CardContent>
          </Card>
          <Card>
            <CardContent className="pt-6">
              <div className="text-center">
                <p className="text-3xl font-bold text-primary-400">{customEvents.length}</p>
                <p className="text-sm text-gray-600 mt-1">Custom Events</p>
              </div>
            </CardContent>
          </Card>
          <Card>
            <CardContent className="pt-6">
              <div className="text-center">
                <p className="text-3xl font-bold text-primary-400">
                  {wedding ? Math.ceil((new Date(wedding.date).getTime() - Date.now()) / (1000 * 60 * 60 * 24)) : 0}
                </p>
                <p className="text-sm text-gray-600 mt-1">Days to Wedding</p>
              </div>
            </CardContent>
          </Card>
        </div>

        {/* Auto-Generated Events */}
        {autoGeneratedEvents.length > 0 && (
          <div>
            <h2 className="text-2xl font-semibold text-gray-900 mb-4">Traditional Events</h2>
            <div className="grid md:grid-cols-2 gap-4">
              {autoGeneratedEvents.map((event) => (
                <EventCard
                  key={event.id}
                  event={event}
                  onDelete={handleDeleteEvent}
                  onRefresh={fetchWeddingAndEvents}
                />
              ))}
            </div>
          </div>
        )}

        {/* Custom Events */}
        {customEvents.length > 0 && (
          <div>
            <h2 className="text-2xl font-semibold text-gray-900 mb-4">Custom Events</h2>
            <div className="grid md:grid-cols-2 gap-4">
              {customEvents.map((event) => (
                <EventCard
                  key={event.id}
                  event={event}
                  onDelete={handleDeleteEvent}
                  onRefresh={fetchWeddingAndEvents}
                />
              ))}
            </div>
          </div>
        )}

        {events.length === 0 && (
          <Card>
            <CardContent className="py-12 text-center">
              <div className="text-6xl mb-4">📅</div>
              <h3 className="text-xl font-semibold text-gray-900 mb-2">No Events Yet</h3>
              <p className="text-gray-600 mb-6">
                Events are automatically generated when you create a wedding. You can also add custom events.
              </p>
              <Button onClick={() => setShowCreateModal(true)}>Add Your First Event</Button>
            </CardContent>
          </Card>
        )}

        {/* Create Event Modal */}
        {wedding && (
          <CreateEventModal
            isOpen={showCreateModal}
            onClose={() => setShowCreateModal(false)}
            weddingId={wedding.id}
            onEventCreated={handleEventCreated}
          />
        )}
      </div>
    </Layout>
  )
}

export default EventsPage
